### ISSUE TITLE
Inconsistent data response on semantic admin endpoint.

### ISSUE THREAD

**Issue by radius314** [LittleGreenViper/BMLT-Root-Server#12]
If you make a request to the semantic admin as such:

`/local_server/server_admin/json.php?admin_action=get_permissions`

And the user you're logging in as has only one service body the response will not be an array.  However if there are more than one it will be.   It's my belief that it should always return a consistent model (in this case, always return an array).  I realize this might break other clients and things will have to be adjusted accordingly.  I will be working around this issue in the interim to not block development on this issue found: https://github.com/radius314/yap/issues/89

One service body (no array):
![https___bmltserver_org_main_server__local_server_server_admin_json_php_admin_action_get_permissions](https://user-images.githubusercontent.com/1850811/42414117-8b544950-81fc-11e8-820b-0796aa4a5d90.png)

More than one service body (array):
![https___bmltserver_org_main_server__local_server_server_admin_json_php_admin_action_get_permissions](https://user-images.githubusercontent.com/1850811/42414122-9904d7ea-81fc-11e8-9cd3-c18e2d5b7f94.png)

**Comment by LittleGreenViper** [comment]
You are correct. There are probably a number of things like this throughout the repo.
The issue is that fixing them (like the gKey issue) may break stuff that is out there.
It will take time to analyze this, and time is something that's in short supply for me, these days.

**Comment by radius314** [comment]
Worked around it, so it’s non-urgent.

**Comment by jbraswell** [comment]
I agree with this issue, but I'm afraid fixing it will break existing contracts for consumers of this API. Can we enumerate the repos of code that use this API, and check the for compatibility? If we can validate it won't break anything downstream, I'll take a look at fixing it.

**Comment by radius314** [comment]
I actually don't care about it anymore and also am worried about Yap breaking at this point.
