### ISSUE TITLE
Duration time inconsistent with leading zeros

### ISSUE THREAD

**Issue by pjaudiomv** [LittleGreenViper/BMLT-Root-Server#17]
I ran into a weird issue there seems to be an inconsistency with meeting duration times appending a leading zero to the beginning or not. I wonder if this has something to do with web server or not. newyorkna bmlt is all fine. Can't seem to repro but haven't spent much time on it.

Examples:

**SEZF from Georgia Region.**

_Has leading Zero_
https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_ids[]=4357

_Does Not_
https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_ids[]=4222

**NERNA**
*EDIT* I fixed NERNAs in the sql database
_Has leading Zero_
https://www.nerna.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_ids[]=417

_Does Not_
https://www.nerna.org/main_server/client_interface/json/?switcher=GetSearchResults&meeting_ids[]=297

**Autonomy Zone**
_Has leading Zero_
https://metrorichna.org/BMLT/main_server/client_interface/json/?switcher=GetSearchResults&meeting_ids[]=656

_Does Not_
https://metrorichna.org/BMLT/main_server/client_interface/json/?switcher=GetSearchResults&meeting_ids[]=657

**Comment by jbraswell** [comment]
@pjaudiomv Is this resolved by 2.11.0? Can this be closed?

**Comment by pjaudiomv** [comment]
im curious how this happens, how is a default_duration_time not set, do these happen in naws imports, or what. this does fix it the inconsistent time format from happening, but im wondering how this happens where no default_duration_time is set or isset is failing idk. 

https://github.com/LittleGreenViper/BMLT-Root-Server/blob/e56873a0b070ef67c86f1c15e3f2a48387ee4c64/main_server/server/c_comdef_server.class.php#L2899

**Comment by jbraswell** [comment]
I don't have a good explanation... I'm gonna close this, unless @LittleGreenViper has any input.
