### ISSUE TITLE
Copy/paste into BMLT field does not stick on save

### ISSUE THREAD

**Issue by Redguy1959** [LittleGreenViper/BMLT-Root-Server#20]
None of my browsers work with copy/paste. Whenever I paste something into a BMLT field I hit space then backspace so the field sticks. It's been that way forever and I always train people on it. If it's the first field being edited you can tell as the Save Changes button doesn't light up after paste until you type something in the field.

Operating systems tested: Windows 7, Windows XP. Browsers tested: Internet Explorer 11, Fastpeak Slimjet, Google Chrome, K-Meleon

**Comment by jbraswell** [comment]
Definitely a legitimate issue. I think the solution is to add onpaste handlers to fields in addition to the existing onchange handler.

**Comment by jbraswell** [comment]
Fixed in 2.11.1
