### ISSUE TITLE
Auto coords calculation on save

### ISSUE THREAD

**Issue by radius314** [LittleGreenViper/BMLT-Root-Server#25]
Currently when you save a change you need to mash the coords button.  It would be great if this happened automatically.  There are cases when it actually does need to be manually set, but this should be the exception to the rule.  Id imagine a setting on a per meeting basis that indicates you want a manual override.  Or it could just be a new button, “Save and do not recalculate coordinates.”  Basically two buttons.

**Comment by jbraswell** [comment]
https://github.com/LittleGreenViper/BMLT-Root-Server/pull/38
