### ISSUE TITLE
Change My Account Settings Button not in right state

### ISSUE THREAD

**Issue by pjaudiomv** [LittleGreenViper/BMLT-Root-Server#28]
When logged in as a server admin, if you go to "My Account" the button defaults to white. If you select to change email address it stays white. if you select to "Change My Password To" it stays white as well. However if you select to change "My Description" it turns grey, whats you type in this field it turns white again. Seems that they all should stay grey untill a change is made.

**Comment by jbraswell** [comment]
This is better in 2.11.1, but still not quite right. Will make it perfect in 2.11.2, maybe.

**Comment by jbraswell** [comment]
I think this is fixed for real now in master... maybe
