### ISSUE TITLE
The NAWS Download Link Is In A Bad Place

### ISSUE THREAD

**Issue by LittleGreenViper** [LittleGreenViper/BMLT-Root-Server#29]
It's immediately above the Delete Button in the Service Body Admin page.

It should either be removed, or moved away from that button.

I guess that could be done with CSS, but it might be easier to move it in the PHP code.

**Comment by jbraswell** [comment]
![image](https://user-images.githubusercontent.com/10187286/46388333-703ad580-c699-11e8-8d4d-d5fdac806b0e.png)

**Comment by jbraswell** [comment]
Fixed in 2.11.2.

**Comment by LittleGreenViper** [comment]
Looks good to me.
