### ISSUE TITLE
new export NAWS dump link not showing on first service body

### ISSUE THREAD

**Issue by radius314** [LittleGreenViper/BMLT-Root-Server#34]
I noticed an issue while testing the new location of the export NAWS dump link (running off latest master sha-1 6a1d3892629a0cd8dfe1c06323ca639eb9869bfa).

When logging in as a serveradmin and going to the Service Body Administration the first service body doesn't have the link.  Even when I navigate away and then go to another and then back, it still doesn't appear.

https://www.dropbox.com/s/swensfxivcyhhgb/naws_dump_link_first_service_body.mov?dl=0

**Comment by jbraswell** [comment]
There are some conditions for whether or not it’s displayed, and those haven’t changed.

**Comment by radius314** [comment]
I see.  I was not aware of them.  Are they documented somewhere to verify?

**Comment by jbraswell** [comment]
Not able to get to a computer right now but I think the service body has to have meetings, and those meetings have to have World IDs.

**Comment by jbraswell** [comment]
Going from memory here - I think that’s it.

**Comment by pjaudiomv** [comment]
the service body itself has to have a 'World Committee Code'

**Comment by radius314** [comment]
Just calling out that with the link on the top, although the functionality is not new, may create a wave of similar questions.

**Comment by jbraswell** [comment]
Could always show the link, and when the user clicks export, prompt them to get a World ID and link to some documentation on what that is and how that works.

**Comment by radius314** [comment]
Seems like a good solution.
