### ISSUE TITLE
Admin UI Press Enter to Search for Meetings

### ISSUE THREAD

**Issue by pjaudiomv** [LittleGreenViper/BMLT-Root-Server#36]
Currently if you want to search for a meeting in the admin interface you have to smash the 'Search for Meetings' button. I hit enter key all the time to nothing :( , it would be nice if the enter key could also complete the search.
This seems to only not work for Firefox.

**Comment by LittleGreenViper** [comment]
I use the Enter key all the time. I specifically designed it to use it.

It can be non-obvious when it is working, as the only indication is the button is replaced by the throbber, which can be beneath the fold.

**Comment by pjaudiomv** [comment]
Updated comment, Seems to only not work for Firefox im using 62.0.3 Mac OS X

**Comment by jbraswell** [comment]
This is fixed in 2.12.0

**Comment by pjaudiomv** [comment]
word just tested, works great. thanks.
