### ISSUE TITLE
Checking admin current session state

### ISSUE THREAD

**Issue by radius314** [LittleGreenViper/BMLT-Root-Server#5]
Starting to implement the session state, and looking for an easy way to verify that the current session is still active.  Not sure how you check this on the mobile app side.  I guess what I'm thinking is that a simple `admin_action=session_check`.  

Background on this is that yap is going to have an admin interface which is going to rely upon BMLT credentials via the semantic admin api.

**Comment by LittleGreenViper** [comment]
There isn’t anything explicit in the API for this, but I could add something, I guess. As long as it was only a flag, it wouldn’t be a security issue.

Still, it would probably be best to use HTTP session tracking, as even if I did add it, it would be months before it would be universally available.

Remember that this is a stateless system, so you could easily track it from your end. You will know if the session is active.

I wouldn’t mind knowing a bit more about how this works.

**Comment by radius314** [comment]
I am using HTTP session tracking with cookies.  Once a user it authenticated (using their BMLT credentials), they are authenticated in the Yap admin portal.  A cookie is stored on the server for that user.  

Upon each subsequent page load of the Yap admin, I want to be able to verify that the session is still active.  What I'm doing now is making a request to `/local_server/server_admin/xml.php?admin_action=get_permissions`. ref: https://github.com/radius314/yap/blob/unstable/functions.php#L515.

The issue with this request, is that it returns a bunch of XML that I wind up dump, creating unnecessary network chatter.  I could make a head request, but I'm unsure of whether or not you will vouch that through session checking.  The basic premise here, is a ping-pong type request-response.  Is this session still active, similar to the `login` action, but not for re-authenticating.  Returning the same body response would work too.  "OK" and "<H1>NOT AUTHORIZED</H1>".

**Comment by LittleGreenViper** [comment]
Hmm... This needs to happen on the HTTP level. It's not a true RESTful interface. GET and POST are treated as one.

I'd need to write some special code. That's the kind of thing that could move a lot of cheese, and require lots of testing. I might not have the bandwidth for it now.

As of now, as long as you have the same session active, you can be assured of a login. There's no time limit, which is one of the reasons that I force-close the session after ten seconds on the admin app.

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by radius314** [comment]
I think you might be conflating things a bit.  I'm literally relying on the session of the BMLT server via a standard HTTP request.  I'll just send a PR.

**Comment by LittleGreenViper** [comment]
Possibly. I'd have to see a state diagram of the request to understand it completely, I guess.

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by radius314** [comment]
Yeah let me put something together, maybe diagram via pull request.  Grokking the session stuff a bit.
